name: Cross Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-linux-cross:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ aarch64-musl ]
    container:
      image: docker://benfred/rust-musl-cross:${{ matrix.target }}
      env:
        RUSTUP_HOME: /root/.rustup
        CARGO_HOME: /root/.cargo
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          sudo python3 -m pip install maturin
          maturin build -b bin --no-sdist -o dist --target aarch64-unknown-linux-musl
      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: dist